# Generated by Django 3.1.7 on 2021-03-22 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beitrag',
            name='dokument',
        ),
        migrations.AddField(
            model_name='dokument',
            name='beitrag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karte.beitrag'),
        ),
    ]
