# Generated by Django 3.1.7 on 2021-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0004_auto_20210516_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='wettbewerb',
            name='jahrBis',
            field=models.IntegerField(null=True),
        ),
    ]
