# Generated by Django 3.1.7 on 2021-07-08 13:34

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0005_wettbewerb_jahrbis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorin',
            options={'ordering': ('nachname',), 'verbose_name_plural': 'Autorinnen'},
        ),
        migrations.AlterField(
            model_name='autorin',
            name='nachname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autorin',
            name='vorname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autorinschule',
            name='jahrgangsstufe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beitrag',
            name='einzel_gruppe',
            field=models.BooleanField(blank=True, default=True, verbose_name='Einzelarbeit (Haken gesetzt=Einzelarbeit, Haken nicht gesetzt=Gruppenarbeit)'),
        ),
        migrations.AlterField(
            model_name='beitrag',
            name='regest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beitrag',
            name='signatur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beitrag',
            name='titel',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='beitrag',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karte.tutor'),
        ),
        migrations.AlterField(
            model_name='beitrag',
            name='umfang',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='beitrag',
            name='zeitraumBis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beitrag',
            name='zeitraumVon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='dokument',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karte.dokumenttyp'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(7.626135, 51.960667), geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='persoenlichkeit',
            name='gnd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nachname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='vorname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wettbewerb',
            name='kurztitel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wettbewerb',
            name='thema',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wettbewerb',
            name='zusammenfassung',
            field=models.TextField(blank=True, default='Zusammenfassung', null=True),
        ),
    ]
