# Generated by Django 3.1.7 on 2021-07-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0006_auto_20210701_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ort',
            name='histName',
            field=models.ManyToManyField(blank=True, to='karte.HistorischerOrt'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='histRegion',
            field=models.ManyToManyField(blank=True, to='karte.HistorischeRegion'),
        ),
    ]
