# Generated by Django 3.1.7 on 2021-07-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0008_auto_20210701_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beitrag',
            name='titel',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='beitrag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karte.beitrag'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karte.dokumenttyp'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='histName',
            field=models.ManyToManyField(blank=True, to='karte.HistorischerOrt'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='histRegion',
            field=models.ManyToManyField(blank=True, to='karte.HistorischeRegion'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wettbewerb',
            name='thema',
            field=models.TextField(null=True),
        ),
    ]
