# Generated by Django 3.1.7 on 2021-07-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0009_auto_20210701_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beitrag',
            name='einzel_gruppe',
            field=models.BooleanField(blank=True, default=True, verbose_name='Einzelarbeit (Haken gesetzt=Einzelarbeit, Haken nicht gesetzt=Gruppenarbeit)'),
        ),
    ]
