# Generated by Django 3.1.7 on 2021-07-01 14:10

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0010_auto_20210701_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ort',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(7.626135, 51.960667), geography=True, srid=4326),
        ),
    ]
