# Generated by Django 3.1.7 on 2021-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0011_auto_20210701_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorin',
            options={'ordering': ('nachname',), 'verbose_name_plural': 'Autorinnen'},
        ),
        migrations.AlterField(
            model_name='beitrag',
            name='umfang',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
