# Generated by Django 3.1.7 on 2021-07-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0012_auto_20210708_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorin',
            options={'ordering': ('nachname', 'vorname'), 'verbose_name_plural': 'Autorinnen'},
        ),
    ]
