# Generated by Django 3.1.7 on 2021-09-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0013_auto_20210708_1354'),
        ('karte', '0006_auto_20210708_1334'),
    ]

    operations = [
    ]
