# Generated by Django 3.1.7 on 2021-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0014_merge_20210901_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jahrgangsstufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufe', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Jahrgangsstufen',
            },
        ),
        migrations.AlterModelOptions(
            name='autorin',
            options={'ordering': ('nachname', 'vorname'), 'verbose_name_plural': 'Autorinnen'},
        ),
        migrations.AlterModelOptions(
            name='beitrag',
            options={'ordering': ('wettbewerb__jahr', 'signatur'), 'verbose_name_plural': 'Beiträge'},
        ),
        migrations.AddField(
            model_name='beitrag',
            name='jahrgaenge',
            field=models.ManyToManyField(blank=True, to='karte.Jahrgangsstufe'),
        ),
    ]
